### ISSUE TITLE
Verify German localization for new app glance functionality

### ISSUE THREAD

**Issue by CometDog** [cheeseisdisgusting/exhale#10]
#9 
Improper internet translations were used to localize the following strings:
- the App Glance sections in src/pkjs/config.js files
- the default switch of the localize_get_app_glance_text function in src/c/localize.c

Verify the strings in Spanish, French, and German with generic locales

**Comment by aaronhktan** [comment]
I've verified and modified the Spanish and French strings. The German ones are still slightly sketch, but I should be able to get some German friends to check it over a bit later.
